### ISSUE TITLE
Cannot get quote by index

### ISSUE THREAD

**Issue by sreiswig** [crazybmanp/RyuZU-bot2#8] opened 2017-11-13 05:36 UTC

**Comment by crazybmanp** [comment] 2017-11-13 06:33
Problem was caused by a wierd scoping bug that only became apperantly on the production environment. fix has been made in c773b61aff5ecabb8e7a971c3ff215ed5c09586b and rolled out

**Closed by crazybmanp** 2017-11-13 06:33 UTC
